# Generated by Django 5.2.4 on 2025-07-21 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Scholarship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='The official title or name of the scholarship.', max_length=200)),
                ('description', models.TextField(help_text='A comprehensive description of the scholarship, its purpose, and what it covers.')),
                ('eligibility', models.TextField(help_text="Detailed criteria students must meet to be eligible (e.g., 'Minimum GPA 3.0', 'For undergraduate students', 'Myanmar citizen only').")),
                ('application_link', models.URLField(blank=True, help_text='Direct link to the external scholarship application website. Optional if a PDF brochure contains all application details.', max_length=500)),
                ('deadline', models.DateField(help_text='The final date by which applications must be submitted.')),
                ('min_gpa', models.DecimalField(blank=True, decimal_places=2, help_text='Optional: The minimum GPA required for this scholarship (e.g., 3.0, 3.5). Leave blank if not applicable.', max_digits=3, null=True)),
                ('country', models.CharField(blank=True, help_text="Optional: The country for which this scholarship is intended (e.g., 'USA', 'Myanmar', 'UK').", max_length=100, null=True)),
                ('major_department', models.CharField(blank=True, help_text="Optional: Specific major(s) or department(s) for which the scholarship is applicable (e.g., 'Computer Science', 'Engineering', 'Any Field').", max_length=200, null=True)),
                ('brochure_pdf', models.FileField(blank=True, help_text='Optional: Upload a PDF document containing the scholarship brochure, detailed application instructions, or forms provided by the teacher/university.', null=True, upload_to='scholarship_brochures/')),
                ('banner_image', models.ImageField(blank=True, help_text='Optional: Upload a relevant banner image or logo for the scholarship.', null=True, upload_to='scholarship_banners/')),
                ('is_active', models.BooleanField(default=True, help_text='Check this box if the scholarship is currently open for applications and should be visible to students.')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Automatically records the date and time when this scholarship record was first created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Automatically updates the date and time whenever this scholarship record is modified.')),
            ],
            options={
                'verbose_name_plural': 'Scholarships',
                'ordering': ['deadline', 'title'],
            },
        ),
    ]
