# Generated by Django 5.2.4 on 2025-07-24 16:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Scholarship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='The official title or name of the scholarship.', max_length=200)),
                ('description', models.TextField(help_text='A comprehensive description of the scholarship, its purpose, and what it covers.')),
                ('eligibility', models.TextField(help_text="Detailed criteria students must meet to be eligible (e.g., 'Minimum GPA 3.0', 'For undergraduate students', 'Myanmar citizen only').")),
                ('application_link', models.URLField(blank=True, help_text='Direct link to the external scholarship application website. Optional if a PDF brochure contains all application details.', max_length=500)),
                ('deadline', models.DateField(help_text='The final date by which applications must be submitted.')),
                ('min_gpa', models.DecimalField(blank=True, decimal_places=2, help_text='Optional: The minimum GPA required for this scholarship (e.g., 3.0, 3.5). Leave blank if not applicable.', max_digits=3, null=True)),
                ('country', models.CharField(blank=True, help_text="Optional: The country for which this scholarship is intended (e.g., 'USA', 'Myanmar', 'UK').", max_length=100, null=True)),
                ('major', models.CharField(choices=[('SE', 'B.C.Sc. (Software Engineering)'), ('BIS', 'B.C.Sc. (Business Information Systems)'), ('KE', 'B.C.Sc. (Knowledge Engineering)'), ('HPC', 'B.C.Sc. (High Performance Computing)'), ('ES', 'B.C.Tech. (Embedded Systems)'), ('CN', 'B.C.Tech. (Communication and Networking)'), ('CSec', 'B.C.Tech. (Cyber Security)')], default='SE', max_length=50)),
                ('major_department', models.CharField(blank=True, choices=[('SE', 'B.C.Sc. (Software Engineering)'), ('BIS', 'B.C.Sc. (Business Information Systems)'), ('KE', 'B.C.Sc. (Knowledge Engineering)'), ('HPC', 'B.C.Sc. (High Performance Computing)'), ('ES', 'B.C.Tech. (Embedded Systems)'), ('CN', 'B.C.Tech. (Communication and Networking)'), ('CSec', 'B.C.Tech. (Cyber Security)')], help_text="Optional: Specific major(s) or department(s) for which the scholarship is applicable (e.g., 'Computer Science', 'Engineering', 'Any Field').", max_length=50, null=True)),
                ('brochure_pdf', models.FileField(blank=True, help_text='Optional: Upload a PDF document containing the scholarship brochure, detailed application instructions, or forms provided by the teacher/university.', null=True, upload_to='scholarship_brochures/')),
                ('banner_image', models.ImageField(blank=True, help_text='Optional: Upload a relevant banner image or logo for the scholarship.', null=True, upload_to='scholarship_banners/')),
                ('is_active', models.BooleanField(default=True, help_text='Check this box if the scholarship is currently open for applications and should be visible to students.')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Automatically records the date and time when this scholarship record was first created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Automatically updates the date and time whenever this scholarship record is modified.')),
            ],
            options={
                'verbose_name_plural': 'Scholarships',
                'ordering': ['deadline', 'title'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('STUDENT', 'Student'), ('FACULTY', 'Faculty'), ('ADMIN', 'Administrator')], default='STUDENT', max_length=10)),
                ('roll_no', models.CharField(blank=True, help_text='Your unique Roll Number (e.g., YKPT-XXXX). Required for Students.', max_length=20, null=True, unique=True)),
                ('major', models.CharField(choices=[('SE', 'B.C.Sc. (Software Engineering)'), ('BIS', 'B.C.Sc. (Business Information Systems)'), ('KE', 'B.C.Sc. (Knowledge Engineering)'), ('HPC', 'B.C.Sc. (High Performance Computing)'), ('ES', 'B.C.Tech. (Embedded Systems)'), ('CN', 'B.C.Tech. (Communication and Networking)'), ('CSec', 'B.C.Tech. (Cyber Security)')], default='SE', max_length=50)),
                ('semester', models.IntegerField(choices=[(1, 'Semester 1'), (2, 'Semester 2'), (3, 'Semester 3'), (4, 'Semester 4'), (5, 'Semester 5'), (6, 'Semester 6'), (7, 'Semester 7'), (8, 'Semester 8'), (9, 'Semester 9'), (10, 'Semester 10')], default=1)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
