# Generated by Django 5.2.4 on 2025-08-02 03:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarships', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scholarship',
            name='major_department',
        ),
        migrations.AddField(
            model_name='scholarship',
            name='posted_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='scholarship',
            name='brochure_pdf',
            field=models.FileField(blank=True, help_text='Optional: Upload a PDF document containing the scholarship brochure.', null=True, upload_to='scholarship_brochures/'),
        ),
        migrations.AlterField(
            model_name='scholarship',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Automatically records the creation date and time.'),
        ),
        migrations.AlterField(
            model_name='scholarship',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Check this box if the scholarship is currently open for applications.'),
        ),
        migrations.AlterField(
            model_name='scholarship',
            name='major',
            field=models.CharField(choices=[('SE', 'B.C.Sc. (Software Engineering)'), ('BIS', 'B.C.Sc. (Business Information Systems)'), ('KE', 'B.C.Sc. (Knowledge Engineering)'), ('HPC', 'B.C.Sc. (High Performance Computing)'), ('ES', 'B.C.Tech. (Embedded Systems)'), ('CN', 'B.C.Tech. (Communication and Networking)'), ('CSec', 'B.C.Tech. (Cyber Security)')], default='SE', help_text='The specific major(s) or department(s) for which the scholarship is applicable.', max_length=50),
        ),
        migrations.AlterField(
            model_name='scholarship',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Automatically updates the date and time whenever the record is modified.'),
        ),
    ]
