# Generated by Django 5.2.4 on 2025-07-22 16:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarships', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_no', models.CharField(help_text='Your unique Roll Number (e.g., YKPT-XXXX)', max_length=20, unique=True)),
                ('major', models.CharField(choices=[('SE', 'B.C.Sc. (Software Engineering)'), ('BIS', 'B.C.Sc. (Business Information Systems)'), ('KE', 'B.C.Sc. (Knowledge Engineering)'), ('HPC', 'B.C.Sc. (High Performance Computing)'), ('ES', 'B.C.Tech. (Embedded Systems)'), ('CN', 'B.C.Tech. (Communication and Networking)'), ('CSec', 'B.C.Tech. (Cyber Security)')], default='CS', max_length=50)),
                ('semester', models.IntegerField(choices=[(1, 'Semester 1'), (2, 'Semester 2'), (3, 'Semester 3'), (4, 'Semester 4'), (5, 'Semester 5'), (6, 'Semester 6'), (7, 'Semester 7'), (8, 'Semester 8'), (9, 'Semester 9'), (10, 'Semester 10')], default=1)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
