# Generated by Django 4.2.23 on 2025-07-31 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarships', '0002_company_testimonial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
