# Generated by Django 5.2.5 on 2025-08-17 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scholarships', '0002_scholarship_wishlisted_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scholarship',
            old_name='created_at',
            new_name='posted_at',
        ),
    ]
