# Generated by Django 5.2.4 on 2025-08-02 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarships', '0002_alter_userprofile_major_alter_userprofile_semester'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='major',
            field=models.CharField(blank=True, choices=[('SE', 'B.C.Sc. (Software Engineering)'), ('BIS', 'B.C.Sc. (Business Information Systems)'), ('KE', 'B.C.Sc. (Knowledge Engineering)'), ('HPC', 'B.C.Sc. (High Performance Computing)'), ('ES', 'B.C.Tech. (Embedded Systems)'), ('CN', 'B.C.Tech. (Communication and Networking)'), ('CSec', 'B.C.Tech. (Cyber Security)')], default='SE', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='semester',
            field=models.IntegerField(blank=True, choices=[(1, 'Semester 1'), (2, 'Semester 2'), (3, 'Semester 3'), (4, 'Semester 4'), (5, 'Semester 5'), (6, 'Semester 6'), (7, 'Semester 7'), (8, 'Semester 8'), (9, 'Semester 9'), (10, 'Semester 10')], default=1, null=True),
        ),
    ]
