# Generated by Django 5.2.4 on 2025-07-22 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarships', '0002_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('STUDENT', 'Student'), ('TEACHER', 'Teacher'), ('STAFF', 'Staff')], default='STUDENT', max_length=10),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='major',
            field=models.CharField(choices=[('CS', 'Computer Science'), ('SE', 'B.C.Sc. (Software Engineering)'), ('BIS', 'B.C.Sc. (Business Information Systems)'), ('KE', 'B.C.Sc. (Knowledge Engineering)'), ('HPC', 'B.C.Sc. (High Performance Computing)'), ('CT', 'Computer Technology'), ('ES', 'B.C.Tech. (Embedded Systems)'), ('CN', 'B.C.Tech. (Communication and Networking)'), ('CSec', 'B.C.Tech. (Cyber Security)')], default='CS', max_length=50),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='roll_no',
            field=models.CharField(blank=True, help_text='Your unique Roll Number (e.g., YKPT-XXXX). Required for Students.', max_length=20, null=True, unique=True),
        ),
    ]
