# Generated by Django 4.2.23 on 2025-08-25 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
    ('scholarships', '0001_initial'),
]


    operations = [
        migrations.RemoveField(
            model_name='testimonial',
            name='outcome',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='major',
            field=models.CharField(blank=True, choices=[('SE', 'B.C.Sc. (Software Engineering)'), ('BIS', 'B.C.Sc. (Business Information Systems)'), ('KE', 'B.C.Sc. (Knowledge Engineering)'), ('HPC', 'B.C.Sc. (High Performance Computing)'), ('ES', 'B.C.Tech. (Embedded Systems)'), ('CN', 'B.C.Tech. (Communication and Networking)'), ('CSec', 'B.C.Tech. (Cyber Security)'), ('CST', 'CST (Have not decided yet)')], help_text='Your major. Required for Students.', max_length=50, null=True),
        ),
    ]
