# Generated by Django 4.2.23 on 2025-07-31 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scholarships', '0003_testimonial_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testimonial',
            name='description',
        ),
    ]
