# Generated by Django 5.2.4 on 2025-07-22 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarships', '0003_userprofile_role_alter_userprofile_major_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='major',
            field=models.CharField(choices=[('SE', 'B.C.Sc. (Software Engineering)'), ('BIS', 'B.C.Sc. (Business Information Systems)'), ('KE', 'B.C.Sc. (Knowledge Engineering)'), ('HPC', 'B.C.Sc. (High Performance Computing)'), ('ES', 'B.C.Tech. (Embedded Systems)'), ('CN', 'B.C.Tech. (Communication and Networking)'), ('CSec', 'B.C.Tech. (Cyber Security)')], default='CS', max_length=50),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('STUDENT', 'Student'), ('FACULTY', 'Faculty'), ('ADMIN', 'Administrator')], default='STUDENT', max_length=10),
        ),
    ]
