# Generated by Django 5.2.5 on 2025-08-17 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scholarships', '0003_rename_created_at_scholarship_posted_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scholarship',
            old_name='posted_at',
            new_name='created_at',
        ),
    ]
