# Generated by Django 5.2.5 on 2025-08-17 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scholarships', '0004_rename_posted_at_scholarship_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='announcement',
            old_name='posted_at',
            new_name='created_at',
        ),
    ]
