# Generated by Django 4.2.23 on 2025-08-04 04:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        # Change this to match your actual 0004 migration file name
        ('scholarships', '0004_auto_20250804_0432'),  # Example - use your actual filename
        # ... other dependencies
    ]
    operations = [
    ]
