# Generated by Django 4.2.23 on 2025-08-26 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scholarships', '0005_alter_scholarship_major_alter_userprofile_major'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testimonial',
            name='technologies',
        ),
    ]
