# Generated by Django 4.2.23 on 2025-08-26 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scholarships', '0006_remove_testimonial_technologies'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testimonial',
            name='graduation_info',
        ),
    ]
