# Generated by Django 5.2.5 on 2025-08-19 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarships', '0006_resource'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='semester',
        ),
        migrations.AddField(
            model_name='scholarship',
            name='level',
            field=models.CharField(blank=True, choices=[('UNDERGRADUATE', 'Undergraduate'), ('GRADUATE', 'Graduate')], help_text='The academic level for which this scholarship is intended.', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='academic_level',
            field=models.CharField(blank=True, choices=[('UNDERGRADUATE', 'Undergraduate'), ('GRADUATE', 'Graduate')], help_text='Your current academic level (Undergraduate or Graduate). Required for Students.', max_length=20, null=True),
        ),
        migrations.DeleteModel(
            name='Resource',
        ),
    ]
