# Generated by Django 4.2.23 on 2025-08-06 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scholarships', '0007_userprofile_bio_userprofile_phone_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Wishlist',
        ),
    ]
