# Generated by Django 4.2.23 on 2025-08-29 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarships', '0007_remove_testimonial_graduation_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='place',
            field=models.CharField(help_text='e.g.main hall/ theatre', max_length=200),
        ),
        migrations.AlterField(
            model_name='scholarship',
            name='country',
            field=models.CharField(blank=True, help_text='Optional', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='scholarship',
            name='major',
            field=models.CharField(choices=[('All', 'All Majors'), ('SE', 'B.C.Sc. (Software Engineering)'), ('BIS', 'B.C.Sc. (Business Information Systems)'), ('KE', 'B.C.Sc. (Knowledge Engineering)'), ('CSec', 'B.C.Sc. (Cyber Security)'), ('HPC', 'B.C.Sc. (High Performance Computing)'), ('ES', 'B.C.Tech. (Embedded Systems)'), ('CN', 'B.C.Tech. (Communication and Networking)')], default='SE', help_text='The specific major(s) or department(s) for which the scholarship is applicable.', max_length=50),
        ),
    ]
