# Generated by Django 4.2.23 on 2025-08-07 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scholarships', '0008_delete_wishlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='profile_picture',
        ),
    ]
