# Generated by Django 4.2.23 on 2025-08-08 17:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('scholarships', '0009_remove_userprofile_bio_remove_userprofile_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scholarship',
            name='wishlisted_by',
            field=models.ManyToManyField(blank=True, related_name='wishlist', to=settings.AUTH_USER_MODEL),
        ),
    ]
